/*
 See the documentation for more options:
 https://github.com/jenkins-infra/pipeline-library/
*/
buildPlugin(
  forkCount: '1C', // run this number of tests in parallel for faster feedback.  If the number terminates with a 'C', the value will be multiplied by the number of available CPU cores
  useContainerAgent: true, // Set to `false` if you need to use Docker for containerized tests
  // NOTE: these are the CI build/test JDKs, which are independent of the minimum
  // runtime Java version. The supported runtime is set by <jenkins.baseline> in
  // pom.xml (2.479 => Java 17 minimum, Java 21 also supported). Linux/JDK 25 gives
  // newest-JDK forward-compatibility coverage; Windows/JDK 21 covers a baseline-
  // supported runtime JDK. (Linux 25 + Windows 21 is the Jenkins project's current
  // recommended matrix, generated by the "Modernize Jenkinsfile" tooling.)
  configurations: [
    [platform: 'linux', jdk: 25],
    [platform: 'windows', jdk: 21],
])
